INSERT INTO member(user_name, first_name, last_name, gender, admin, password)
 VALUES
	('NickLarson', 'Nick', 'Larson', True, FALSE, '123'),
	('ParisDong', 'Paris', 'Dong', True, FALSE, '123'),
	('PascalPorche', 'Pascal', 'Porche', True, FALSE, '123'),
	('TroyHusted', 'Troy', 'Husted', True, FALSE, '123'),
	('CallawaySpahr', 'Callaway', 'Spahr', True, FALSE, '123'),
	('OwenRung', 'Owen', 'Rung', True, FALSE, '123'),
	('WesleyBrand', 'Wesley', 'Brand', True, FALSE, '123'),
	('ChaseErskine', 'Chase', 'Erskine', True, FALSE, '123'),
	('CalebMorford', 'Caleb', 'Morford', True, FALSE, '123'),
	('AldenSoto', 'Alden', 'Soto', True, FALSE, '123'),
	('JackBendure', 'Jack', 'Bendure', True, FALSE, '123'),
	('WillSnider', 'Will', 'Snider', True, FALSE, '123'),
	('JaySeabrum', 'Jay', 'Seabrum', True, FALSE, '123'),
	('MannyPreston de Miranda', 'Manny', 'Preston de Miranda', True, FALSE, '123'),
	('MagnusLehan', 'Magnus', 'Lehan', True, FALSE, '123'),
	('RyanSievers', 'Ryan', 'Sievers', True, FALSE, '123'),
	('HassanShahzad', 'Hassan', 'Shahzad', True, FALSE, '123'),
	('JackBjerke', 'Jack', 'Bjerke', True, FALSE, '123'),
	('EthanBenedict', 'Ethan', 'Benedict', True, FALSE, '123'),
	('MichaelDriscoll', 'Michael', 'Driscoll', True, FALSE, '123'),
	('OsbaldoDe La Cruz', 'Osbaldo', 'De La Cruz', True, FALSE, '123'),
	('NavChidambaram', 'Nav', 'Chidambaram', True, FALSE, '123'),
	('MakenzieDaugherty', 'Makenzie', 'Daugherty', False, FALSE, '123'),
	('GraceMcKenna', 'Grace', 'McKenna', False, FALSE, '123'),
	('AlexDoner', 'Alex', 'Doner', True, FALSE, '123'),
	('RyanAlbright', 'Ryan', 'Albright', True, FALSE, '123'),
	('WylieRomanow', 'Wylie', 'Romanow', True, FALSE, '123'),
	('ZoePeacock', 'Zoe', 'Peacock', False, FALSE, '123'),
	('MeganBrady', 'Megan', 'Brady', False, FALSE, '123'),
	('DuncanKliphuis', 'Duncan', 'Kliphuis', True, FALSE, '123'),
	('RichardTran', 'Richard', 'Tran', True, FALSE, '123'),
	('LoganAnchick', 'Logan', 'Anchick', True, FALSE, '123'),
	('EliBaumgarten', 'Eli', 'Baumgarten', True, FALSE, '123'),
	('BenBixler', 'Ben', 'Bixler', True, FALSE, '123'),
	('HarryCroley', 'Harry', 'Croley', True, FALSE, '123'),
	('CameronDavis', 'Cameron', 'Davis', True, FALSE, '123'),
	('TristanDoan', 'Tristan', 'Doan', True, FALSE, '123'),
	('WestonHirschauer', 'Weston', 'Hirschauer', True, FALSE, '123'),
	('AlexHuynh', 'Alex', 'Huynh', True, FALSE, '123'),
	('AlexJackson', 'Alex', 'Jackson', True, FALSE, '123'),
	('LizJanko', 'Liz', 'Janko', False, FALSE, '123'),
	('AustinKatzer', 'Austin', 'Katzer', True, FALSE, '123'),
	('Ann DeeKindrick', 'Ann Dee', 'Kindrick', True, FALSE, '123'),
	('AbhimanyuKumar', 'Abhimanyu', 'Kumar', True, FALSE, '123'),
	('ShoukenL', 'Shouken', 'L', True, FALSE, '123'),
	('Victoria (Toria)Lindenmuth', 'Victoria (Toria)', 'Lindenmuth', True, FALSE, '123'),
	('ViktoriaMeyerhoff', 'Viktoria', 'Meyerhoff', True, FALSE, '123'),
	('MalcolmMurray', 'Malcolm', 'Murray', True, FALSE, '123'),
	('NickNeely', 'Nick', 'Neely', True, FALSE, '123'),
	('GrantNorman', 'Grant', 'Norman', True, FALSE, '123'),
	('RohanPathak', 'Rohan', 'Pathak', True, FALSE, '123'),
	('NylaPrassad', 'Nyla', 'Prassad', False, FALSE, '123'),
	('TylerRadke', 'Tyler', 'Radke', True, FALSE, '123'),
	('SeanSpindler', 'Sean', 'Spindler', True, FALSE, '123'),
	('ColsonSurran', 'Colson', 'Surran', True, FALSE, '123'),
	('JacobWehmeyer', 'Jacob', 'Wehmeyer', True, FALSE, '123'),
	('MaeYustin', 'Mae', 'Yustin', False, FALSE, '123'),
	('PaulZhang', 'Paul', 'Zhang', True, FALSE, '123'),
	('finesser', 'riley', 'iwanaga', TRUE, TRUE, 'finesser')
