INSERT INTO member(user_name, first_name, last_name, gender, role, password)
 VALUES
	('NickLarson', 'Nick', 'Larson', 'male', 'user', '123'),
	('ParisDong', 'Paris', 'Dong', 'male', 'user', '123'),
	('PascalPorche', 'Pascal', 'Porche', 'male', 'user', '123'),
	('TroyHusted', 'Troy', 'Husted', 'male', 'user', '123'),
	('CallawaySpahr', 'Callaway', 'Spahr', 'male', 'user', '123'),
	('OwenRung', 'Owen', 'Rung', 'male', 'user', '123'),
	('WesleyBrand', 'Wesley', 'Brand', 'male', 'user', '123'),
	('ChaseErskine', 'Chase', 'Erskine', 'male', 'user', '123'),
	('CalebMorford', 'Caleb', 'Morford', 'male', 'user', '123'),
	('AldenSoto', 'Alden', 'Soto', 'male', 'user', '123'),
	('JackBendure', 'Jack', 'Bendure', 'male', 'user', '123'),
	('WillSnider', 'Will', 'Snider', 'male', 'user', '123'),
	('JaySeabrum', 'Jay', 'Seabrum', 'male', 'user', '123'),
	('MannyPreston de Miranda', 'Manny', 'Preston de Miranda', 'male', 'user', '123'),
	('MagnusLehan', 'Magnus', 'Lehan', 'male', 'user', '123'),
	('RyanSievers', 'Ryan', 'Sievers', 'male', 'user', '123'),
	('HassanShahzad', 'Hassan', 'Shahzad', 'male', 'user', '123'),
	('JackBjerke', 'Jack', 'Bjerke', 'male', 'user', '123'),
	('EthanBenedict', 'Ethan', 'Benedict', 'male', 'user', '123'),
	('MichaelDriscoll', 'Michael', 'Driscoll', 'male', 'user', '123'),
	('OsbaldoDe La Cruz', 'Osbaldo', 'De La Cruz', 'male', 'user', '123'),
	('NavChidambaram', 'Nav', 'Chidambaram', 'male', 'user', '123'),
	('MakenzieDaugherty', 'Makenzie', 'Daugherty', 'female', 'user', '123'),
	('GraceMcKenna', 'Grace', 'McKenna', 'female', 'user', '123'),
	('AlexDoner', 'Alex', 'Doner', 'male', 'user', '123'),
	('RyanAlbright', 'Ryan', 'Albright', 'male', 'user', '123'),
	('WylieRomanow', 'Wylie', 'Romanow', 'male', 'user', '123'),
	('ZoePeacock', 'Zoe', 'Peacock', 'female', 'user', '123'),
	('MeganBrady', 'Megan', 'Brady', 'female', 'user', '123'),
	('DuncanKliphuis', 'Duncan', 'Kliphuis', 'male', 'user', '123'),
	('RichardTran', 'Richard', 'Tran', 'male', 'user', '123'),
	('LoganAnchick', 'Logan', 'Anchick', 'male', 'user', '123'),
	('EliBaumgarten', 'Eli', 'Baumgarten', 'male', 'user', '123'),
	('BenBixler', 'Ben', 'Bixler', 'male', 'user', '123'),
	('HarryCroley', 'Harry', 'Croley', 'male', 'user', '123'),
	('CameronDavis', 'Cameron', 'Davis', 'male', 'user', '123'),
	('TristanDoan', 'Tristan', 'Doan', 'male', 'user', '123'),
	('WestonHirschauer', 'Weston', 'Hirschauer', 'male', 'user', '123'),
	('AlexHuynh', 'Alex', 'Huynh', 'male', 'user', '123'),
	('AlexJackson', 'Alex', 'Jackson', 'male', 'user', '123'),
	('LizJanko', 'Liz', 'Janko', 'male', 'user', '123'),
	('AustinKatzer', 'Austin', 'Katzer', 'male', 'user', '123'),
	('Ann DeeKindrick', 'Ann Dee', 'Kindrick', 'male', 'user', '123'),
	('AbhimanyuKumar', 'Abhimanyu', 'Kumar', 'male', 'user', '123'),
	('ShoukenL', 'Shouken', 'L', 'male', 'user', '123'),
	('Victoria (Toria)Lindenmuth', 'Victoria (Toria)', 'Lindenmuth', 'male', 'user', '123'),
	('ViktoriaMeyerhoff', 'Viktoria', 'Meyerhoff', 'male', 'user', '123'),
	('MalcolmMurray', 'Malcolm', 'Murray', 'male', 'user', '123'),
	('NickNeely', 'Nick', 'Neely', 'male', 'user', '123'),
	('GrantNorman', 'Grant', 'Norman', 'male', 'user', '123'),
	('RohanPathak', 'Rohan', 'Pathak', 'male', 'user', '123'),
	('NylaPrassad', 'Nyla', 'Prassad', 'female', 'user', '123'),
	('TylerRadke', 'Tyler', 'Radke', 'male', 'user', '123'),
	('SeanSpindler', 'Sean', 'Spindler', 'male', 'user', '123'),
	('ColsonSurran', 'Colson', 'Surran', 'male', 'user', '123'),
	('JacobWehmeyer', 'Jacob', 'Wehmeyer', 'male', 'user', '123'),
	('MaeYustin', 'Mae', 'Yustin', 'female', 'user', '123'),
	('PaulZhang', 'Paul', 'Zhang', 'male', 'user', '123'),
	('finesser', 'riley', 'iwanaga', 'male', 'admin', 'finesser')
